AppBundle\Entity\CategoryProject:
    type: entity
    table: category_project
    indexes:
        category_id:
            columns:
                - category_id
        project_id:
            columns:
                - project_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        assignData:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: assign_data
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        project:
            targetEntity: Project
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
