AppBundle\Entity\Comment:
    type: entity
    table: comment
    indexes:
        post_id:
            columns:
                - post_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: user_id
        message:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        data:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        active:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        postId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: post_id
    lifecycleCallbacks: {  }
