AppBundle\Entity\PostCategory:
    type: entity
    table: post_category
    indexes:
        post_id:
            columns:
                - post_id
        category_id:
            columns:
                - category_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        post:
            targetEntity: Post
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                post_id:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
