AppBundle\Entity\Profile:
    type: entity
    table: profile
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        bio:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        github:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        bitbucket:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        linkedin:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        twitter:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        facebook:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        instagram:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        youtube:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
