AppBundle\Entity\Tag:
    type: entity
    table: tag
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tag:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
    lifecycleCallbacks: {  }
