AppBundle\Entity\UserProject:
    type: entity
    table: user_project
    indexes:
        user_id:
            columns:
                - user_id
        project_id:
            columns:
                - project_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        assignData:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: assign_data
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        project:
            targetEntity: Project
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
